static const e_char  char_table[128] = 
{
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::whitespace,
  e_char::whitespace,
  e_char::whitespace,
  e_char::whitespace,
  e_char::whitespace,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::invalid,
  e_char::whitespace,
  /* ! */ e_char::invalid,
  /* " */ e_char::invalid,
  /* # */ e_char::invalid,
  /* $ */ e_char::invalid,
  /* % */ e_char::invalid,
  /* & */ e_char::invalid,
  /* ' */ e_char::invalid,
  /* ( */ e_char::parenthesis,
  /* ) */ e_char::parenthesis,
  /* * */ e_char::operators,
  /* + */ e_char::operators,
  /* , */ e_char::invalid,
  /* - */ e_char::operators,
  /* . */ e_char::dot,
  /* / */ e_char::operators,
  /* 0 */ e_char::zero,
  /* 1 */ e_char::nonzero_digit,
  /* 2 */ e_char::nonzero_digit,
  /* 3 */ e_char::nonzero_digit,
  /* 4 */ e_char::nonzero_digit,
  /* 5 */ e_char::nonzero_digit,
  /* 6 */ e_char::nonzero_digit,
  /* 7 */ e_char::nonzero_digit,
  /* 8 */ e_char::nonzero_digit,
  /* 9 */ e_char::nonzero_digit,
  /* : */ e_char::invalid,
  /* ; */ e_char::invalid,
  /* < */ e_char::invalid,
  /* = */ e_char::operators,
  /* > */ e_char::invalid,
  /* ? */ e_char::invalid,
  /* @ */ e_char::invalid,
  /* A */ e_char::character,
  /* B */ e_char::character,
  /* C */ e_char::character,
  /* D */ e_char::character,
  /* E */ e_char::character,
  /* F */ e_char::character,
  /* G */ e_char::character,
  /* H */ e_char::character,
  /* I */ e_char::character,
  /* J */ e_char::character,
  /* K */ e_char::character,
  /* L */ e_char::character,
  /* M */ e_char::character,
  /* N */ e_char::character,
  /* O */ e_char::character,
  /* P */ e_char::character,
  /* Q */ e_char::character,
  /* R */ e_char::character,
  /* S */ e_char::character,
  /* T */ e_char::character,
  /* U */ e_char::character,
  /* V */ e_char::character,
  /* W */ e_char::character,
  /* X */ e_char::character,
  /* Y */ e_char::character,
  /* Z */ e_char::character,
  /* [ */ e_char::invalid,
  /* \ */ e_char::invalid,
  /* ] */ e_char::invalid,
  /* ^ */ e_char::invalid,
  /* _ */ e_char::invalid,
  /* ` */ e_char::invalid,
  /* a */ e_char::character,
  /* b */ e_char::character,
  /* c */ e_char::character,
  /* d */ e_char::character,
  /* e */ e_char::character,
  /* f */ e_char::character,
  /* g */ e_char::character,
  /* h */ e_char::character,
  /* i */ e_char::character,
  /* j */ e_char::character,
  /* k */ e_char::character,
  /* l */ e_char::character,
  /* m */ e_char::character,
  /* n */ e_char::character,
  /* o */ e_char::character,
  /* p */ e_char::character,
  /* q */ e_char::character,
  /* r */ e_char::character,
  /* s */ e_char::character,
  /* t */ e_char::character,
  /* u */ e_char::character,
  /* v */ e_char::character,
  /* w */ e_char::character,
  /* x */ e_char::character,
  /* y */ e_char::character,
  /* z */ e_char::character,
  /* { */ e_char::invalid,
  /* | */ e_char::invalid,
  /* } */ e_char::invalid,
  /* ~ */ e_char::invalid,
  /*del*/ e_char::invalid
};
